INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Book Report", "English", 10000, "2019-01-01", "2019-05-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Close Reading", "English", 500, "2019-02-01", "2019-06-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Diorama", "English", 50000, "2019-01-01", "2019-08-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Science Fair", "Science", 40000, "2019-01-22", "2019-05-22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Presentation", "History", 1000, "2019-02-18", "2019-08-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Final Paper", "Psychology", 15000, "2019-01-05", "2019-07-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Timeline", "History", 850, "2019-03-17", "2019-06-17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Concert", "Music", 80000, "2019-01-01", "2019-10-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Solo", "Music", 2000, "2019-04-01", "2019-05-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) values ("Group Presentation", "Spanish", 11000, "2019-01-01", "2019-04-01");

INSERT INTO users(name, age) values ("Charlie", 23);
INSERT INTO users(name, age) values ("Greg", 50);
INSERT INTO users(name, age) values ("Roseanne", 3);
INSERT INTO users(name, age) values ("Clem", 88);
INSERT INTO users(name, age) values ("Helena", 50);
INSERT INTO users(name, age) values ("Reese", 24);
INSERT INTO users(name, age) values ("Gary", 20);
INSERT INTO users(name, age) values ("Ray", 18);
INSERT INTO users(name, age) values ("Vicky", 41);
INSERT INTO users(name, age) values ("Shoshanna", 38);
INSERT INTO users(name, age) values ("Edgar", 75);
INSERT INTO users(name, age) values ("DaRon", 9);
INSERT INTO users(name, age) values ("Allison", 11);
INSERT INTO users(name, age) values ("Ricky", 10);
INSERT INTO users(name, age) values ("Renito", 9);
INSERT INTO users(name, age) values ("Diallo", 16);
INSERT INTO users(name, age) values ("Nykah", 14);
INSERT INTO users(name, age) values ("Angel", 12);
INSERT INTO users(name, age) values ("Chauncey", 12);
INSERT INTO users(name, age) values ("Mekhi", 11);

INSERT INTO pledges(user_id, amount, project_id) values (5, 50, 5);
INSERT INTO pledges(user_id, amount, project_id) values (6, 50, 6);
INSERT INTO pledges(user_id, amount, project_id) values (1, 50, 4);
INSERT INTO pledges(user_id, amount, project_id) values (2, 100, 3);
INSERT INTO pledges(user_id, amount, project_id) values (2, 25, 1);
INSERT INTO pledges(user_id, amount, project_id) values (3, 50, 2);
INSERT INTO pledges(user_id, amount, project_id) values (20, 100, 6);
INSERT INTO pledges(user_id, amount, project_id) values (4, 50, 8);
INSERT INTO pledges(user_id, amount, project_id) values (6, 25, 7);
INSERT INTO pledges(user_id, amount, project_id) values (7, 25, 10);
INSERT INTO pledges(user_id, amount, project_id) values (8, 50, 9);
INSERT INTO pledges(user_id, amount, project_id) values (15, 50, 3);
INSERT INTO pledges(user_id, amount, project_id) values (14, 50, 4);
INSERT INTO pledges(user_id, amount, project_id) values (13, 25, 10);
INSERT INTO pledges(user_id, amount, project_id) values (12, 50, 9);
INSERT INTO pledges(user_id, amount, project_id) values (11, 100, 8);
INSERT INTO pledges(user_id, amount, project_id) values (10, 50, 1);
INSERT INTO pledges(user_id, amount, project_id) values (9, 50, 2);
INSERT INTO pledges(user_id, amount, project_id) values (8, 50, 5);
INSERT INTO pledges(user_id, amount, project_id) values (11, 50, 6);
INSERT INTO pledges(user_id, amount, project_id) values (2, 50, 7);
INSERT INTO pledges(user_id, amount, project_id) values (13, 50, 9);
INSERT INTO pledges(user_id, amount, project_id) values (14, 25, 10);
INSERT INTO pledges(user_id, amount, project_id) values (20, 50, 8);
INSERT INTO pledges(user_id, amount, project_id) values (15, 100, 4);
INSERT INTO pledges(user_id, amount, project_id) values (16, 50, 5);
INSERT INTO pledges(user_id, amount, project_id) values (17, 50, 3);
INSERT INTO pledges(user_id, amount, project_id) values (18, 50, 2);
INSERT INTO pledges(user_id, amount, project_id) values (19, 100, 1);
INSERT INTO pledges(user_id, amount, project_id) values (20, 50, 6);
