INSERT INTO users (name, age) VALUES ("Maru", 22);
INSERT INTO users (name, age) VALUES ("Jimmy", 52);
INSERT INTO users (name, age) VALUES ("Johnny", 47);
INSERT INTO users (name, age) VALUES ("Franky", 90);
INSERT INTO users (name, age) VALUES ("Timmy", 62);
INSERT INTO users (name, age) VALUES ("Jimmy", 25);
INSERT INTO users (name, age) VALUES ("Tommy", 26);
INSERT INTO users (name, age) VALUES ("Billy", 53);
INSERT INTO users (name, age) VALUES ("Bobby", 23);
INSERT INTO users (name, age) VALUES ("Benny", 18);
INSERT INTO users (name, age) VALUES ("Tony", 36);
INSERT INTO users (name, age) VALUES ("Richy", 73);
INSERT INTO users (name, age) VALUES ("Eddie", 53);
INSERT INTO users (name, age) VALUES ("Minnie", 73);
INSERT INTO users (name, age) VALUES ("Winnie", 25);
INSERT INTO users (name, age) VALUES ("Kiki", 33);
INSERT INTO users (name, age) VALUES ("Jennie", 33);
INSERT INTO users (name, age) VALUES ("Kimmie", 52);
INSERT INTO users (name, age) VALUES ("Missy", 42);
INSERT INTO users (name, age) VALUES ("Larry", 24);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Crazy Bridge", "Construction", 6000000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Nightclub", "Construction", 3000000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Funny Invention", "Nonsense", 99000000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pointless Movie", "Art", 1000000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Useless Tool", "Engineering", 200000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Big Thing", "Construction", 8000000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Chain Restaurant", "Construction", 100000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Big Bridge", "Construction", 3000000, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Shady Bridge", "Construction", 500, "dunno", "dunno");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Great Park", "Construction", 500000, "dunno", "dunno");
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 3);
